name: fly.io test workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - test
          - prod
      dry_run:
        description: 'Dry run only'
        required: false
        type: boolean
        default: false