name: fly.io test workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - test
          - prod
      dry_run:
        description: 'Dry run only'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl ssh console --app fctc-gitea-mariadb-0cd1a12c --command 'sh ./some_script.sh'
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
